{ pkgs }: {
    deps = [
      pkgs.glibcLocales
      pkgs.cacert
      pkgs.pango
      pkgs.harfbuzz
      pkgs.glib
      pkgs.ghostscript
      pkgs.unzip
      pkgs.openal
      pkgs.libpulseaudio
      pkgs.libGLU
      pkgs.libGL
      pkgs.gtk2-x11
      pkgs.gdk-pixbuf
      pkgs.ffmpeg-full
      pkgs.rustc
      pkgs.libxcrypt
      pkgs.libiconv
      pkgs.cargo
      pkgs.portmidi
      pkgs.libpng
      pkgs.libjpeg
      pkgs.freetype
      pkgs.fontconfig
      pkgs.SDL2_ttf
      pkgs.SDL2_mixer
      pkgs.SDL2_image
      pkgs.SDL2
      pkgs.openssl
      pkgs.zlib
      pkgs.xcodebuild
      pkgs.pkg-config
      pkgs.libffi
      pkgs.python311Packages.flask
      pkgs.cowsay
    ];
}